# Lednice - Kompletní konfigurace pro samoobslužnou lednici
# Uložte tento soubor do /config/packages/zamek2.yaml
# Poté v configuration.yaml přidejte: homeassistant: packages: !include_dir_named packages

# ============================================
# INPUT HELPERS
# ============================================

input_boolean:
  lednice_guest_logged_in:
    name: "Lednice - Host přihlášen"
    icon: mdi:account-check
    initial: false

input_text:
  lednice_current_pin:
    name: "Lednice - Aktuální PIN"
    initial: ""
    max: 10

  lednice_current_room:
    name: "Lednice - Aktuální pokoj"
    initial: ""
    max: 20

# ============================================
# AUTOMATIZACE
# ============================================

automation:
  # Automatizace 1: Nastavit přihlášení po úspěšném ověření PIN
  - id: lednice_set_logged_in_on_pin_verified
    alias: "Lednice - Nastavit přihlášení po PIN"
    description: "Nastaví boolean na ON když je PIN úspěšně ověřen"
    trigger:
      - platform: event
        event_type: lednice_pin_verified
        event_data:
          valid: true
    action:
      # NEJDŘÍV nastavit room, PAK boolean - aby karta měla data připravená
      - service: input_text.set_value
        target:
          entity_id: input_text.lednice_current_room
        data:
          value: "{{ trigger.event.data.room }}"
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.lednice_guest_logged_in
    mode: restart

  # Automatizace 2: Vymazat data při odhlášení
  - id: lednice_clear_data_on_logout
    alias: "Lednice - Vymazat data při odhlášení"
    description: "Automaticky vymaže konzumaci a PIN když se host odhlásí"
    trigger:
      - platform: state
        entity_id: input_boolean.lednice_guest_logged_in
        to: "off"
    action:
      - service: input_text.set_value
        target:
          entity_id: input_text.lednice_current_room
        data:
          value: ""
      - service: input_text.set_value
        target:
          entity_id: input_text.lednice_current_pin
        data:
          value: ""
    mode: single

  # Automatizace 3: Neúspěšné ověření PIN
  - id: lednice_invalid_pin_notification
    alias: "Lednice - Neplatný PIN"
    description: "Zobrazí chybu při neplatném PIN"
    trigger:
      - platform: event
        event_type: lednice_pin_verified
        event_data:
          valid: false
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.lednice_guest_logged_in
      - service: input_text.set_value
        target:
          entity_id: input_text.lednice_current_room
        data:
          value: ""
    mode: single

  # Automatizace 4: Automatické odhlášení po 5 minutách
  - id: lednice_auto_logout_after_5_minutes
    alias: "Lednice - Automatické odhlášení po 5 minutách"
    description: "Automaticky odhlásí hosta po 5 minutách nečinnosti"
    trigger:
      - platform: state
        entity_id: input_boolean.lednice_guest_logged_in
        to: "on"
        for:
          minutes: 5
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.lednice_guest_logged_in
    mode: restart
